version: '3.7'

services:
  db:
    image: postgres:12.2-alpine
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  web:
    build: ./docker/python
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./code:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
